name: create_release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'SDK Version'     
        required: true
        default: '1.0.0'
jobs:
  tests:
    name: create_release
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: "ü§ñ Install Pods"
      run:  |
          pod install

    # Update new version
    - shell: bash
      env:
          GB_SDK_VERSION: ${{ github.event.inputs.version }}
      run:  |
          sh scripts/setup_version.sh -v "$GB_SDK_VERSION"

    - name: "ü§ñ Generate Pull Request and merge"
      env:
          GB_SDK_VERSION: ${{ github.event.inputs.version }}
      run: |
          git branch releases/RELEASE-"$GB_SDK_VERSION"
          git checkout releases/RELEASE-"$GB_SDK_VERSION"
          git status
          git add GBSwiftLogger.podspec
          git add GBSwiftLogger.xcodeproj/project.pbxproj
          git add docs/
          git commit -m "Release v$GB_SDK_VERSION"
          git push --set-upstream origin releases/RELEASE-"$GB_SDK_VERSION"
          git checkout main
          git fetch
          git pull
          git merge releases/RELEASE-"$GB_SDK_VERSION"
          git push

    - name: "ü§ñ Setup ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - name: "ü§ñ Setup Fastlane"
      run:  |
          bundle install

    - name: "‚úèÔ∏è Get last created TAG"
      id: get-last-tag
      run:  echo "::set-output name=LAST_TAG::$(git describe --tags $(git rev-list --tags --max-count=1))"


    - name: "‚úèÔ∏è  Generate changelog from last TAG"
      id: get-changelog
      run: |
          bundle exec fastlane changelog tag:${{ steps.get-last-tag.outputs.LAST_TAG }}

    - name: "‚úèÔ∏è Read changelog.txt"
      id: changelog-file
      uses: juliangruber/read-file-action@v1
      with:
        path: ./fastlane/changelog.txt

    - name: "‚úèÔ∏è Print Changelog"
      run: |
          echo "${{ steps.changelog-file.outputs.content }}"

    - name: "üöÄ Create GH Release"
      id: release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        body: |
          ${{ steps.changelog-file.outputs.content }}
        draft: false
        prerelease: false
